### ISSUE TITLE
Log the user in automatically

### ISSUE THREAD

**Issue by dinhtungdu** [10up/cypress-wp-utils#31]
### Is your enhancement related to a problem? Please describe.

If we can skip the login step, it'll be a huge time saver.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
Logged-in session could be shared across all tests: [(Cypress docs)](https://docs.cypress.io/faq/questions/using-cypress-faq#How-do-I-preserve-cookies-localStorage-in-between-my-tests)

> **How do I preserve cookies / localStorage in between my tests?**
>
> By default, Cypress automatically [clears all cookies before each test](https://docs.cypress.io/api/commands/clearcookies) to prevent state from building up.
>
> You can preserve specific cookies across tests using the [Cypress.Cookies api](https://docs.cypress.io/api/cypress-api/cookies):
>
> ```javascript
> // now any cookie with the name 'session_id' will
> // not be cleared before each test runs
> Cypress.Cookies.defaults({
>   preserve: 'session_id',
> })
> ```

Doing that, we are able to move the call of `cy.login()` to the upper level from `beforeEach` to `before` hook. It will help to reduce login actions to 1 per test suite.

Also consider performing a single call of `cy.login()` from `support/index.js` to see if it's possible to perform single login for across multiple test suites.

Also I want to notice that it's testers responsibility to decide if they want to trade off the test isolation for the performance.

This also might break our library tests in the future if some new commands and their test suites will rely on logging other users rather than the default `admin`.

**Comment by cadic** [comment]
Update: a single call of `cy.login()` from `support/index.js` does not work for cypress in cli mode: https://github.com/10up/cypress-wp-utils/pull/46#issuecomment-1085869034
