### ISSUE TITLE
`createTerm` doesn't work with custom hierarchical taxonomy

### ISSUE THREAD

**Issue by dinhtungdu** [10up/cypress-wp-utils#50]
### Describe the bug

The command throws errors trying to create a new term if there isn't any term exists.

### Steps to Reproduce

1. Create a custom hierarchical taxonomy.
2. Write test using `cy.createTerm`.
3. Run the test and see error.

### Screenshots, screen recording, code snippet

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/5423135/161897402-6f9c9555-a23e-46e5-83e0-9ce7758bdc1a.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
Reopened after discussion with @dinhtungdu 

The issue is related to https://github.com/10up/simple-podcasting/, which has [CSS](https://github.com/10up/simple-podcasting/blob/trunk/assets/css/podcasting-edit-term.css#L1-L3) hiding the parent term dropdown:

```css
.taxonomy-podcasting_podcasts .term-parent-wrap {
	display: none;
}
```

It causes assertion error in the `createTerm` command, because it can't access the hidden element.

The suggested fix is to conditionally skip interaction with `#parent` dropdown if parent term is set to default `-1`
