### ISSUE TITLE
Bump WordPress and PHP minimums

### ISSUE THREAD

**Issue by vikrampm1** [10up/cypress-wp-utils#71]
Bump WP & PHP Minimums to the following
 
- [x] WordPress to 5.7
- [ ] PHP to 7.4
- [ ] Remove any no-longer-needed conditional code for older version support.
- [x] Take a look at adjusting our testing matrices, if applicable.
- [ ] Bump the minimums in plugin documentation and header fields.

**Comment by cadic** [comment]
@Sidsector9 do you want someone else to pick this up?

We are experiencing failed WP minimum (5.2) test with the new PHP 8.2 release which is default at GitHub action.

Seems it will be fixed within the current issue?

> [08-Dec-2022 06:12:44 UTC] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/html/wp-includes/script-loader.php on line 757

Curly races was deprecated since PHP 7 and now it was turned into an error at PHP 8.2.

**Comment by Sidsector9** [comment]
@cadic this is fixed but the `create-term.js` test is failing. Should we fix this in a separate issue?
